### ISSUE TITLE
Looper, lastPosition, mouseCurr and transform being constantly recalculated even when mouse is stationary

### ISSUE THREAD

**Issue by oyeanuj** [brycedorn/react-intense#5]
Hey @brycedorn, an issue that I notice when running this is the `looper`, `mouseCurr`, `lastPosition`, `transform` state variables are being constantly re-calculated even when the mouse is not being touched or moved. 

Is this intended? 

(_I imagine this is why it leads to high CPU usage on my computer, since the component is being re-rendered given the constant state re-calculation?_)

**Comment by oyeanuj** [comment]
@brycedorn Any thoughts here?

**Comment by brycedorn** [comment]
this is a valid issue. possible refactor:
 - return `false` from `positionTarget()` if [this check](https://github.com/brycedorn/react-intense/blob/master/lib/ReactIntense.js#L101) fails, otherwise `true`
 - place `positionTarget()` at the beginning of [`loop()`](https://github.com/brycedorn/react-intense/blob/master/lib/ReactIntense.js#L198)
 - only update `looper` if `positionTarget()` returns `true`
I can try this & see if it helps.

**Comment by oyeanuj** [comment]
@brycedorn That would be awesome. Hopefully, it will cut down on the CPU usage and make this component more usable - already a great concept and execution!

**Comment by brycedorn** [comment]
hey @oyeanuj, just merged that change & should lessen the CPU load!

unfortunately due to the nature of `window.requestAnimationFrame` there's no way to prevent the mouse event from firing, but there's now a threshold check before updating state & calculating the position of the image.
